services:
  - type: web
    name: tiktok-recipe-extractor
    runtime: python
    rootDir: Tiktok Extractor/Innovation Hour
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
